# Name of blog
name: Jihoon Lee

#Short description (goes below the title; it will also be used in the RSS feed)
description: Profile

# Your name, as you want it to appear underneath each post and in the footer
author: Jihoon Lee



theme: jekyll-theme-minimal
